version: '3.1'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php

  postgres:
    image: postgres:14.10
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "root"
      POSTGRES_DB: "testdb"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

